"""empty message

Revision ID: 206132e6a264
Revises: 944629875a77
Create Date: 2024-09-16 16:33:49.302606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206132e6a264'
down_revision = '944629875a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('post_description', sa.Text(), nullable=True))
        batch_op.drop_column('alt')
        batch_op.drop_column('uri')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('alt', sa.TEXT(), nullable=True))
        batch_op.drop_column('post_description')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
