"""adding summary column

Revision ID: 4a741a032b2b
Revises: 
Create Date: 2024-09-15 19:02:26.813378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a741a032b2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_addresses')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=250), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('summary')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    op.create_table('_alembic_tmp_addresses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('instagram', sa.VARCHAR(length=200), nullable=True),
    sa.Column('twitter', sa.VARCHAR(length=200), nullable=True),
    sa.Column('facebook', sa.VARCHAR(length=200), nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=200), nullable=True),
    sa.Column('location', sa.VARCHAR(length=120), nullable=False),
    sa.Column('tel', sa.VARCHAR(length=16), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
