"""adding summary column to non nullable

Revision ID: 944629875a77
Revises: 4a741a032b2b
Create Date: 2024-09-15 19:06:18.059546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944629875a77'
down_revision = '4a741a032b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
